name: Build LaTeX document
on: [push]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: Rindrics/latex-action@master
        with:
          working_directory: .
          root_file: 'manuscript.tex'
          args: ''
      - name: Upload pdf
        uses: actions/upload-artifact@v1
        with:
          name: Download
          path: manuscript.pdf
